name: polkadart
repository: https://github.com/leonardocustodio/polkadart

sdkPath: "../encointer-wallet-flutter/.flutter"

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**
  - examples

scripts:
  pub-get:
    run: >-
      dart run melos exec -- \
      flutter pub get
    description: "Get pub dependencies"

  test:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart test --no-chain-stack-traces --ignore-timeouts --coverage="coverage" --concurrency=1'

  coverage:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart run coverage:format_coverage --lcov --in=coverage --out=coverage/coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib'
  
  format:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart format . --set-exit-if-changed'
  
  analyze:
    run: dart run melos exec --scope="${SCOPE:-*}" -c 1 --fail-fast -- 'dart analyze --fatal-infos .'